# Generated by Django 4.2.24 on 2025-12-16 14:32

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("listing_title", models.CharField(blank=True, max_length=255)),
                ("listing_summary", models.CharField(blank=True, max_length=255)),
                ("social_text", models.CharField(blank=True, max_length=255)),
                ("introduction", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 6),
                            ("quote", 14),
                            ("embed", 17),
                            ("call_to_action", 18),
                            ("table", 19),
                            ("typed_table", 23),
                            ("accordion", 27),
                            ("stat_block", 32),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "group": "1. Text blocks",
                                    "icon": "title",
                                    "label": "Heading",
                                    "template": "components/streamfield/heading_block.html",
                                },
                            ),
                            1: (
                                "ukgwa.core.blocks.RichTextBlock",
                                (),
                                {"group": "1. Text blocks", "label": "Rich text"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "If checked, this will make the alt text empty.",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 2),
                                        ("caption", 3),
                                        ("alt_text", 4),
                                        ("image_is_decorative", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            8: ("wagtail.blocks.PageChooserBlock", (), {}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 8), ("link_text", 3)]],
                                {},
                            ),
                            10: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                            11: ("wagtail.blocks.CharBlock", (), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("url", 10), ("link_text", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.StreamBlock",
                                [[("internal_link", 9), ("external_link", 12)]],
                                {"required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 7), ("attribution", 3), ("link", 13)]],
                                {},
                            ),
                            15: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            16: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("description", 15), ("embed", 16)]],
                                {
                                    "group": "2. Media and embed blocks",
                                    "label": "Embed",
                                },
                            ),
                            18: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("core.CallToActionSnippet",),
                                {
                                    "group": "3. Callouts and reusable snippets",
                                    "label": "Call To Action",
                                    "template": "components/streamfield/call_to_action_block.html",
                                },
                            ),
                            19: ("ukgwa.core.blocks.TableBlock", (), {}),
                            20: ("wagtail.blocks.FloatBlock", (), {}),
                            21: (
                                "ukgwa.core.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            22: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("numeric", 20), ("rich_text", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 3), ("table", 22)]],
                                {},
                            ),
                            24: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 24), ("content", 11)]],
                                {},
                            ),
                            26: ("wagtail.blocks.ListBlock", (25,), {}),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("sections", 26)]],
                                {},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter the statistic number. This will be displayed in a large font size.",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a short sentence describing the statistic. This will be displayed in a smaller font size.",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("number", 28),
                                        ("sentence", 29),
                                        ("text", 3),
                                        ("link", 13),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"max_num": 3, "min_num": 1},
                            ),
                            32: ("wagtail.blocks.StructBlock", [[("stats", 31)]], {}),
                        },
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="IndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("listing_title", models.CharField(blank=True, max_length=255)),
                ("listing_summary", models.CharField(blank=True, max_length=255)),
                ("social_text", models.CharField(blank=True, max_length=255)),
                ("introduction", models.TextField(blank=True)),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
