# Generated by Django 4.2.24 on 2025-12-18 14:56

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 6),
                    ("quote", 14),
                    ("embed", 17),
                    ("call_to_action", 18),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "1. Text blocks",
                            "icon": "title",
                            "label": "Heading",
                            "template": "components/streamfield/heading_block.html",
                        },
                    ),
                    1: (
                        "ukgwa.core.blocks.RichTextBlock",
                        (),
                        {"group": "1. Text blocks", "label": "Rich text"},
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, this will make the alt text empty.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("image_is_decorative", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    8: ("wagtail.blocks.PageChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 8), ("link_text", 3)]],
                        {},
                    ),
                    10: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 10), ("link_text", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal_link", 9), ("external_link", 12)]],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("attribution", 3), ("link", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    16: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("description", 15), ("embed", 16)]],
                        {"group": "2. Media and embed blocks", "label": "Embed"},
                    ),
                    18: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.CallToActionSnippet",),
                        {
                            "group": "3. Callouts and reusable snippets",
                            "label": "Call To Action",
                            "template": "components/streamfield/call_to_action_block.html",
                        },
                    ),
                },
            ),
        ),
    ]
