# Generated by Django 4.2.24 on 2025-12-18 16:26

from django.db import migrations, models

import wagtail.fields

import ukgwa.core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0002_alter_informationpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="highlighted_links",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                block_lookup={
                    0: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 0), ("link_text", 1)]],
                        {},
                    ),
                },
                default=ukgwa.core.mixins.get_default_link,
            ),
        ),
        migrations.AddField(
            model_name="informationpage",
            name="highlighted_links_heading",
            field=models.CharField(default="", max_length=255),
        ),
    ]
