# Generated by Django 4.2.24 on 2025-12-16 14:31

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.PageChooserBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "secondary_navigation",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.PageChooserBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_navigation",
                    wagtail.fields.StreamField(
                        [("column", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank if no header required.",
                                    "required": False,
                                },
                            ),
                            1: ("wagtail.blocks.PageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 1), ("title", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("links", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_links",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.PageChooserBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use the page's own title",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("title", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "footer_logo_cloud",
                    wagtail.fields.StreamField(
                        [("logo", 6)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "If checked, this will make the alt text empty.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 0),
                                        ("caption", 1),
                                        ("alt_text", 2),
                                        ("image_is_decorative", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("logo", 4), ("url", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
