# Generated by Django 4.2.24 on 2025-12-17 21:59

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Navigation text",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1), ("external_link", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=wagtail.fields.StreamField(
                [("column", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank if no header required.",
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Navigation text",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 1), ("title", 2), ("external_link", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("links", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Navigation text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="secondary_navigation",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title",
                            "label": "Navigation text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("title", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
