# Generated by Django 4.2.24 on 2025-12-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_alter_navigationsettings_footer_links_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="footer_logo_cloud",
        ),
    ]
