# Generated by Django 4.2.24 on 2025-12-19 14:07

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessagessettings",
            name="active_alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemmessagessettings",
            name="description_alert",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="systemmessagessettings",
            name="title_alert",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
